# Generated by Django 5.2 on 2025-04-10 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='profiles.catalogindustry')),
            ],
        ),
        migrations.CreateModel(
            name='MenteeDesiredField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.catalogfield')),
            ],
        ),
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('development_goals', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_fields', models.ManyToManyField(related_name='desired_by_mentees', through='profiles.MenteeDesiredField', to='profiles.catalogfield')),
            ],
        ),
        migrations.AddField(
            model_name='menteedesiredfield',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.menteeprofile'),
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.company')),
            ],
        ),
        migrations.CreateModel(
            name='MentorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.catalogfield')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.mentorprofile')),
            ],
            options={
                'unique_together': {('mentor', 'field')},
            },
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='specializations',
            field=models.ManyToManyField(related_name='mentor_specializations', through='profiles.MentorSpecialization', to='profiles.catalogfield'),
        ),
        migrations.CreateModel(
            name='MentorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.mentorprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
            ],
            options={
                'unique_together': {('mentor', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='skills',
            field=models.ManyToManyField(related_name='mentors', through='profiles.MentorSkill', to='profiles.skill'),
        ),
        migrations.CreateModel(
            name='MenteeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.menteeprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
            ],
            options={
                'unique_together': {('mentee', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='skills',
            field=models.ManyToManyField(related_name='mentees', through='profiles.MenteeSkill', to='profiles.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='menteedesiredfield',
            unique_together={('mentee', 'field')},
        ),
    ]
