# Generated by Django 5.2 on 2025-04-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MENTEE', 'Mentee'), ('MENTOR', 'Mentor')], default='MENTEE', max_length=10),
        ),
    ]
