services:
  web:
    build: .
    command: gunicorn profile_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - profile_db

  profile_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - static_volume:/app/staticfiles
    environment:
      POSTGRES_DB: profile_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
