services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      # Пример подключения к базе через DATABASE_URL (используйте настройки, соответствующие вашему проекту)
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
    volumes:
      - .:/app  # если хотите монтировать локальные изменения (для разработки)

volumes:
  postgres_data:
