# Generated by Django 5.2 on 2025-04-22 11:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("session_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenteeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mentor_id", models.IntegerField()),
                ("mentee_id", models.IntegerField()),
                (
                    "score",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_rating",
                        to="session_app.session",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["mentee_id"], name="ratings_men_mentee__6a88f8_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MentorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mentor_id", models.IntegerField()),
                ("mentee_id", models.IntegerField()),
                (
                    "score",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_review",
                        to="session_app.session",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["mentor_id"], name="ratings_men_mentor__724188_idx"
                    )
                ],
            },
        ),
    ]
