# Generated by Django 5.2 on 2025-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mentor_id",
                    models.IntegerField(help_text="Mentor ID from Profile Service"),
                ),
                (
                    "start_ts",
                    models.DateTimeField(
                        help_text="Start of the availability interval"
                    ),
                ),
                (
                    "end_ts",
                    models.DateTimeField(help_text="End of the availability interval"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Recurring availability (e.g., weekly)"
                    ),
                ),
            ],
            options={
                "ordering": ["start_ts"],
                "indexes": [
                    models.Index(
                        fields=["mentor_id", "start_ts"],
                        name="session_app_mentor__c8b54d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mentor_id",
                    models.IntegerField(help_text="Mentor ID from Profile Service"),
                ),
                (
                    "mentee_id",
                    models.IntegerField(help_text="Mentee ID from Profile Service"),
                ),
                ("start_ts", models.DateTimeField(help_text="Session start time")),
                ("end_ts", models.DateTimeField(help_text="Session end time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        help_text="Booking status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_ts"],
                "indexes": [
                    models.Index(
                        fields=["mentor_id", "start_ts"],
                        name="session_app_mentor__6605b7_idx",
                    ),
                    models.Index(
                        fields=["mentee_id", "status"],
                        name="session_app_mentee__6f8176_idx",
                    ),
                ],
            },
        ),
    ]
